### ISSUE TITLE
Code cannot be saved in the webpage

### ISSUE THREAD

**Issue by sniffsky** [google/tie#98] opened 2017-04-04 16:57 UTC
I finished the question 2 (compiled successfully and got tests passed) and moved forward to question 3. When I went back to question 2 (click "2" in the process bar) to review the code, the code has been reset and my code was not saved.

**Comment by eyurko** [comment] 2017-04-04 17:30
Definitely an issue we've had -- how would you propose fixing this?

**Comment by luofei11** [comment] 2017-04-04 17:59
Can we use cookie to do this, since we don't have concept of server and session? @eyurko

**Comment by jianhaolyu** [comment] 2017-04-04 18:02
Can we just let chrome or any other browser to cache the code?

**Comment by sniffsky** [comment] 2017-04-04 18:12
Thank you for reply! I do not have specific details yet but the basic two ideas is to use backend database or web cookie. Thanks! @eyurko

**Comment by eyurko** [comment] 2017-04-04 18:44
@luofei11 we do keep some concept of a session -- check the TranscriptObjectFactory / SnapshotObjectFactory.

Also, this is a duplicate of #54.

**Comment by seanlip** [comment] 2017-04-04 19:31
Copying comments from #54 and closing it since this thread seems to have progressed farther. Noting @eyurko's comment from there, too:

> Generally, we'd like to be able to preserve student code on a problem if they navigate between questions or if they refresh the page, but we preprocess the code before saving it in CodeEvalResult. This suggests that it would be worth saving the unprocessed, raw student code as part of the snapshot as well, otherwise we'd have to reverse the preprocess step, which would be needlessly expensive.

My suggestion would be to use localStorage/sessionStorage, since we don't have a backend database. I recommend coming up with a brief technical description of the proposed solution (what namespace are you going to use, for example) before trying to implement it.

**Comment by luofei11** [comment] 2017-04-04 20:24
@seanlip I would suggest using localStorage as it stores data with no expiration date.

**Comment by wmcalyj** [comment] 2017-04-05 17:33
@seanlip Can you please assign me this issue or add me to the collaborator since I am working with Kaikai @sniffsky on this issue together.

**Closed** 2017-04-12 23:38 UTC
Labels: new feature
