### ISSUE TITLE
Changing the function name results in error 

### ISSUE THREAD

**Issue by abinash-behera** [google/tie#107] opened 2017-04-04 18:35 UTC
Executing code after changing the function name displays error and breaks the output console.

**Reproduction Steps:**

1. Open the app.html file in chrome
2. Go to Sample Question 1 (Any sample question would do)
3. Change the function name to any name of your choice
4. Press 'Run'

**Actual Output:**
![screenshot from 2017-04-04 11 30 38](https://cloud.githubusercontent.com/assets/15383817/24672656/6258f370-192a-11e7-89da-288a69a611ed.png)

**Comment by eyurko** [comment] 2017-04-04 18:36
Duplicate of #37.

**Closed** 2017-04-04 18:52 UTC
Labels: duplicate
