### ISSUE TITLE
[Performance Test] The result of performance test is unstable

### ISSUE THREAD

**Issue by jianhaolyu** [google/tie#164] opened 2017-04-06 18:11 UTC
In the 4th sample question, rle, a performance test is used.
However, the result of the performance test is unstable. Eventually, it indicates me that I should try to make my solution in linear time complexity, while my solution is actually in linear complexity.
When I ran my solution again, it passed.
However, I cannot reproduce this problem.

**Comment by seanlip** [comment] 2017-04-26 00:11
Closing as duplicate of #206.

**Closed by seanlip** 2017-04-26 00:11 UTC
Labels: feedback flow
