### ISSUE TITLE
Description of question i18n not clear

### ISSUE THREAD

**Issue by jianjinjian** [google/tie#88] opened 2017-04-04 00:07 UTC
The description/examples of this question could be more detailed, as `dog->d1g` is a valid case according to the description but failed here:

<img width="1331" alt="screen shot 2017-04-03 at 1 43 08 pm" src="https://cloud.githubusercontent.com/assets/26879373/24636333/77197fba-188e-11e7-9f26-6e2aeab5d426.png">

Maybe like below:
An abbreviation of a word follows the form `<first character><length of the middle of the string><last character>`. Below are some examples of word abbreviations:
a) it                   --> it    (no abbreviation)
b) d|o|g            --> dog (no abbreviation)
c) i|nternationalizatio|n  --> i18n

**Comment by seanlip** [comment] 2017-04-04 01:14
Good catch! Including @apicardgoog because he authored the original question; @apicardgoog, do you have any thoughts on how much hinting/description you want to give here?

**Comment by apicardgoog** [comment] 2017-04-04 01:16
I'm open to modifications but I'm not sure what to recommend here. I would like the candidate to think about edge cases on their own. Maybe we could phrase it as "An abbreviation of a word follows the form <first character><length of the middle of the string><last character> if it shortens the word"?

**Comment by eyurko** [comment] 2017-04-04 06:58
I'd contend (and I just said something similar on another issue) that part of the point of these questions is to leave the description somewhat open-ended, as we're trying to mimic an interview setting rather than giving an exact specification of expected inputs and outputs from the get-go. To that end, we shouldn't give too many examples (especially of ones with edge cases). I think the student should be able to glean the intention of the "abbreviate" function from the name of it (since something that is the same length or longer is not abbreviated).

Just my two cents.

**Comment by seanlip** [comment] 2017-04-04 07:11
I agree that we should not enumerate all edge cases in advance, or specify a full set of inputs and outputs covering all corner cases.

However, I think that the requirements of the problem need to be clear, otherwise the problem is ambiguous and there is no one to ask clarifying questions to (which is the main difficulty here). I don't really think that the name of the function alone is sufficient to deduce the purpose of the function.

I can think of two possibilities (there may be others):
- Have some sort of way for students to "ask questions". This could be as simple as having a question mark button in the bottom right and allowing them to select, multiple-choice style, clarifying questions from it. That way, although they might not be able to practice coming up with questions on their own, at least they get a feel for what sort of thing to ask.
- Use a formulation similar to what @apicardgoog suggested -- i.e., describe the problem clearly ("only abbreviate the word if the resulting word is shorter") but leave the student to figure out the implications of this requirement.

Appreciate further thoughts.

**Comment by eyurko** [comment] 2017-04-04 07:18
I actually really like the idea of the question mark + clarifying questions button if we're trying to encourage good interview behavior. I think we could do both things rather easily, though the nuance around how to do the clarifying questions well would probably warrant a longer discussion. I'd say let's start with Antoine's suggestion and then keep the clarifying questions thing as an option for future development.

**Comment by seanlip** [comment] 2017-04-05 00:07
Fixed in #114. Thanks, @jianjinjian!

**Closed by seanlip** 2017-04-05 00:07 UTC
Labels: question schema fixes, TODO: find solution
