### ISSUE TITLE
Record user code before it's processed, so we can recreate user state on refresh / navigation change.

### ISSUE THREAD

**Issue by apicardgoog** [google/tie#54] opened 2017-03-17 21:53 UTC
You told me to write this.

**Comment by seanlip** [comment] 2017-03-17 22:07
Hm -- could we have a more detailed description, please? (How to reproduce the problem, what is expected, what is observed, etc.)

**Comment by eyurko** [comment] 2017-03-17 22:11
ugh fine I'll do it

**Comment by eyurko** [comment] 2017-03-17 22:12
Generally, we'd like to be able to preserve student code on a problem if they navigate between questions or if they refresh the page, but we preprocess the code before saving it in CodeEvalResult. This suggests that it would be worth saving the unprocessed, raw student code as part of the snapshot as well, otherwise we'd have to reverse the preprocess step, which would be needlessly expensive.

**Comment by seanlip** [comment] 2017-04-04 19:32
Closing as duplicate of #98.

**Closed by seanlip** 2017-04-04 19:32 UTC
Labels: infrastructure
