### ISSUE TITLE
Cannot import packages

### ISSUE THREAD

**Issue by cwcai633** [google/tie#87] opened 2017-04-03 23:30 UTC
When I tried to import some packages, I got an ImportError. Here is an example,
![screenshot from 2017-04-03 16 26 37](https://cloud.githubusercontent.com/assets/5900958/24635763/7d806142-188a-11e7-9a76-a1b5858f28f0.png)

**Comment by seanlip** [comment] 2017-04-04 19:25
Closing as duplicate of #100.

**Closed by seanlip** 2017-04-04 19:25 UTC
Labels: infrastructure, TODO: find solution
