### ISSUE TITLE
Unstable feedback

### ISSUE THREAD

**Issue by ouyangyuxin** [google/tie#129] opened 2017-04-05 17:37 UTC
The feedback given by the APP is unstable.
E.g:

def reverseWords(str):
    newStr = ""
    stack = []
    for i in range(0, len(str)):
        if str[i] != ' ':
            stack.append(str[i])
        else:
            newStr += getWord(stack) + " "
(commented line)    if (len(stack) > 0):
(commented line)        newStr += getWord(stack)
    return newStr 

def getWord(stack):
    word = ""
    while (len(stack) > 0):
        word += stack.pop()
    return word

Submitting the above code directly (first run), the feedback is as follows:

[10:26:54 AM] Try running your code on 'new code' on paper. What's the result?

However, submitting the uncomment code above first (which is the correct solution) and then comment and re-submit, the feedback is as follows:

[10:36:53 AM] Your code produced the following result:

Input: "   this  is \t a    whitespace  test" 
Output: "   siht  si \t a    ecapsetihw  " 

However, the expected output is:

"   siht  si \t a    ecapsetihw  tset" 

Could you fix this?

**Comment by eyurko** [comment] 2017-04-05 18:14
WAI -- the first feedback is part of a BuggyOutput, so it's part of a series of hints trying to get the student to discover the bug in their code.

**Comment by seanlip** [comment] 2017-04-05 19:47
While this is working as intended, I am curious about the sequence of events which led this to be perceived as an issue, since this might indicate some possible confusion in the user experience. @ouyangyuxin, would you mind explaining the context behind this bug? Did the different feedback surprise you when you saw it, and, if so, is there any way we could call it out better?

**Comment by seanlip** [comment] 2017-04-08 05:02
@ouyangyuxin ping?

**Comment by ouyangyuxin** [comment] 2017-04-17 06:22
Actually I don't think it's really a big problem since it's working as it's supposed to be. I found this "bug" simply because I intended to find bugs and I do not think users would use the App in the way I did. However, if there's really a need to make the App's UX "better", probably we can simply try to make the output consistent by always showing the hint from BuggyOutput.

**Comment by seanlip** [comment] 2017-04-18 16:32
OK. It sounds like this isn't actually a bug, so, closing. (Thanks for the follow-up, @ouyangyuxin!)

**Closed by seanlip** 2017-04-18 16:32 UTC
Labels: TODO: needs detail, TODO: triage
