### ISSUE TITLE
Question 2 gives wrong tip in the case the function always returns false.

### ISSUE THREAD

**Issue by rujunm** [google/tie#101] opened 2017-04-04 17:19 UTC
If we make the function always return false, it says "Try running your code on '))((' on paper. Did you expect that result?". This suggestion is useless, because the input '))((' should get false.

**Comment by eyurko** [comment] 2017-04-04 17:24
Thanks for filing -- please make sure to add the the clear reproduction steps (starting from a clean client), screenshots and expected/observed behavior, as discussed for filing an issue.

**Comment by rujunm** [comment] 2017-04-04 17:28
Thanks for your reply. In my case, the entire code should be:

def isBalanced(s):
        return False

Click run then you should get that tip.

**Comment by eyurko** [comment] 2017-04-04 18:18
Please add screenshots as well, for posterity.

Thanks!

**Comment by luofei11** [comment] 2017-04-04 18:29
This seems to be similar to #85.

**Comment by seanlip** [comment] 2017-04-04 19:26
Closing as duplicate.

**Closed by seanlip** 2017-04-04 19:26 UTC
Labels: question schema fixes, TODO: needs detail
