### ISSUE TITLE
Better to keep user's code when they navigating different questions

### ISSUE THREAD

**Issue by lumig242** [google/tie#109] opened 2017-04-04 20:10 UTC
Currently, if user navigate to another problem, they will lose all the work on current problem even without a warning message. 

1. Do some work on Q2
![image](https://cloud.githubusercontent.com/assets/4253578/24676382/9f86c54e-1937-11e7-9b2b-a945657c2d7d.png)

2. Click question 3
![image](https://cloud.githubusercontent.com/assets/4253578/24676406/b1d930e2-1937-11e7-9d3a-67e46ea14821.png)

3. Then you lose all your work on Q2
![image](https://cloud.githubusercontent.com/assets/4253578/24676429/c6e36674-1937-11e7-9f2c-71fd0df822bd.png)
 

This can be very frustrating for users if they just navigate to another problem by accident, or they are stuck on the current one and they wish to work on another problem and come back later. We might keep user's work in session or at least add an alert message warning that they are about to lose all the current work.

**Comment by UK-7** [comment] 2017-04-04 20:13
Seems like a duplicate of issue #98
There's a lot of discussion progress on it too

**Comment by eyurko** [comment] 2017-04-04 21:19
Closing, as is a duplicate of #98 and there's been more progress there.

**Closed by eyurko** 2017-04-04 21:19 UTC
Labels: duplicate
